version: '{branch}.{build}'
image: Visual Studio 2019
configuration: release
platform: x86
init:
- ps: >-
    $env:commit = $env:appveyor_repo_commit.SubString(0,7)

    Update-AppveyorBuild -Version ("{0}-{1}-{2}" -f $env:appveyor_repo_branch,$env:appveyor_build_number,$env:commit )
environment:
  VSVER: 16.0 
  matrix:
  - MSVC: 19
    RUNTIME_LINKAGE: static
    ICU_VERSION: 57.1
    ICU_LINKAGE: static
    QTDIR: C:\Qt\5.15\msvc2019
    QT_VERSION: 5.15.0
    QT_LINKAGE: static
install:
- cmd: >-
    %QTDIR%\bin\qtenv2.bat

    set QTDIR

    if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64

    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86

    set QTBIN=%QTDIR%\bin
build_script:
- cmd: >-

    cd C:\projects\blackchocobo

    cmake -G Ninja -DCMAKE_INSTALL_PREFIX=C:\projects\blackchocobo\Black_Chocobo-continuous-win32\ --config=Release CMakeLists.txt

    ninja install

    windeployqt --no-compiler-runtime Black_Chocobo-continuous-win32\bin\Black_Chocobo.exe

    echo "" > Black_Chocobo-continuous-win32\bin\settings.ini

    dir Black_Chocobo-continuous-win32

    7z a -tzip Black_Chocobo-continuous-win32.zip Black_Chocobo-continuous-win32 -r

    del /f Black_Chocobo-continuous-win32\bin\settings.ini

    makensis.exe /X"SetCompressor /FINAL lzma" deploy\bchoco.nsi

artifacts:
- path: Black_Chocobo-continuous-win32.zip
  name: blackchocobo-zip
  
- path: Black_Chocobo-continuous-win32-installer.exe
  name: blackchocobo-installer

deploy:
- provider: GitHub
  tag: continuous
  description: continuous
  auth_token:
    secure: yG66EEKasiTmuCDPStbz0nVsvcETsQlnpDD2ScfNWUwT81kKfALCVFRTPMrp6R6E
  artifact: blackchocobo-zip,blackchocobo-installer
  force_update: true
branches:
  except:
    - /^continuous$/
