os:
 - linux

matrix:
 exclude:
# Only do coverity or coverage build on Linux when the compiler is gcc
  - os: linux
    compiler: clang
    env: COVERITY=1
    env: COVERAGE=1
# Don't build with clang on Linux
  - os: linux
    compiler: clang
compiler: 
- gcc

before_script: 
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then sudo apt-get install libqt4-dev qt4-qmake libssl-dev; fi
- $CXX --version


script: 
- mkdir build_blackchocobo
- cd build_blackchocobo
- qmake ../Black_Chocobo.pro
- make -j2

language: cpp
