language: cpp
dist: xenial
osx_image: xcode10.3

os:
 - linux
 - osx

before_install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-xenial -y;
    sudo apt-get update -qq;
    fi

#MAC OS
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
    fi

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get -y install build-essential qt5-default qt515tools qt515base qt515declarative g++-8 qt515quickcontrols2 zsync;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    fi

#MAC OS
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew upgrade qt5;
    brew upgrade cmake;
    chmod -R 755 /usr/local/opt/qt5/*;
    fi

script:
- git clone https://github.com/sithlord48/ff7tk.git
- cd ff7tk
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    source /opt/qt*/bin/qt*-env.sh;
    cmake -S. -DCMAKE_INSTALL_PREFIX=/usr -DFORMATS=OFF -DUTILS=OFF;
    sudo make install;
    fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
    cmake -S. -DFORMATS=OFF -DUTILS=OFF;
    make install;
    fi
- export VERSION=continuous
- cd ..
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    cmake CMakeLists.txt -Dff7tk_DIR=/usr/lib/x86_64-linux-gnu/cmake/ff7tk -Dff7tkWidgets_DIR=/usr/lib/x86_64-linux-gnu/cmake/ff7tk -DCMAKE_INSTALL_PREFIX=/usr;
    make -j 2;
    make DESTDIR=appdir install; find appdir/;
    cpack;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH;
    mv ./appdir/usr/share/blackchocobo/lang ./appdir/usr/bin;
    cp /usr/share/ff7tk/lang/*.qm ./appdir/usr/bin/lang/;
    rmdir ./appdir/usr/share/blackchocobo;
    ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage;
    fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    cmake -S. -Dff7tk_DIR=/usr/local/lib/cmake/ff7tk/ -Dff7tkWidgets_DIR=/usr/local/lib/cmake/ff7tk/;
    make -j 2;
    cpack;
    fi

after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq ;
    mv Black_Chocobo-*.tar.xz Black_Chocobo-continuous-linux-x86_64.tar.xz;
    bash ./upload.sh Black_Chocobo-continuous*;
    fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    mv Black_Chocobo-*.dmg Black_Chocobo-continuous-macos.dmg;
    bash ./upload.sh Black_Chocobo-continuous-macos.dmg;
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
