language: cpp
sudo: required
dist: xenial

os:
 - linux
 - osx

before_install: 
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-xenial -y;
    sudo apt-get update -qq;
    fi

#MAC OS
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update > /dev/null;
    fi

install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    sudo apt-get -y install build-essential qt5-default qt515tools qt515base g++-8 zsync; 
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90;
    fi

#MAC OS
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew upgrade qt5;
    chmod -R 755 /usr/local/opt/qt5/*;
    fi

script:
- export VERSION=continuous;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    source /opt/qt*/bin/qt*-env.sh;
    qmake Black_Chocobo.pro;
    make -j 4;
    make INSTALL_ROOT=appdir install; find appdir/;
    wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
    chmod a+x linuxdeployqt*.AppImage;
    unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH;
    ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage;
    fi
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    export QTDIR="/usr/local/opt/qt5";
    export PATH="$QTDIR/bin:$PATH";
    qmake Black_Chocobo.pro;
    make -j 4;
    mkdir -p Black_Chocobo.app/Contents/MacOS/lang;
    mv lang/*.qm Black_Chocobo.app/Contents/MacOS/lang/;
    macdeployqt Black_Chocobo.app/ -dmg;
    fi

after_success:
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq ;
    bash ./upload.sh Black_Chocobo*.AppImage*;
    fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    mv Black_Chocobo*.dmg* Black_Chocobo-continuous*.dmg*;
    bash ./upload.sh Black_Chocobo*.dmg*;
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
